//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBoy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album_SB
    {
        public Album_SB()
        {
            this.Track_Recording_Reln = new HashSet<Track_Recording_Reln>();
            this.Track_Album_Reln = new HashSet<Track_Album_Reln>();
        }
    
        public string MB_Release_ID { get; set; }
        public string Album_Name { get; set; }
        public Nullable<System.DateTime> Release_Date { get; set; }
        public string Release_Year { get; set; }
        public string Album_Awards { get; set; }
        public string Album_Links { get; set; }
        public string Album_Content { get; set; }
        public Nullable<int> Album_Image_ID { get; set; }
        public string Album_Type { get; set; }
        public string Album_Status { get; set; }
        public string Album_Quality { get; set; }
        public string Album_Packaging { get; set; }
        public string Album_Language { get; set; }
        public string Album_Country { get; set; }
        public string Album_Lablel { get; set; }
        public string Label_Disambiguation { get; set; }
        public string Album_Script { get; set; }
        public string Album_Barcode { get; set; }
        public byte[] Album_Image { get; set; }
    
        public virtual ICollection<Track_Recording_Reln> Track_Recording_Reln { get; set; }
        public virtual ICollection<Track_Album_Reln> Track_Album_Reln { get; set; }
    }
}
