//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBoy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist_SB
    {
        public Artist_SB()
        {
            this.Track_Artist_Reln = new HashSet<Track_Artist_Reln>();
        }
    
        public string MB_Artist_ID { get; set; }
        public string Artist_Name { get; set; }
        public string Artist_Type { get; set; }
        public Nullable<System.DateTime> Artist_DOB { get; set; }
        public Nullable<System.DateTime> Artist_DOD { get; set; }
        public string Artist_Begin { get; set; }
        public string Artist_Gender { get; set; }
        public string Artist_Country { get; set; }
        public string Artist_Awards { get; set; }
        public string Artist_Links { get; set; }
        public string Artist_Content { get; set; }
        public Nullable<int> Artist_Image_ID { get; set; }
    
        public virtual ICollection<Track_Artist_Reln> Track_Artist_Reln { get; set; }
    }
}
