//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBoy
{
    using System;
    using System.Collections.Generic;
    
    public partial class ID_SB
    {
        public string Hash { get; set; }
        public string MB_Track_ID { get; set; }
        public string Fingerprint { get; set; }
        public string Duration { get; set; }
        public string FilePath { get; set; }
        public string Times_played { get; set; }
        public Nullable<System.DateTime> Last_played { get; set; }
    
        public virtual Track_SB Track_SB { get; set; }
    }
}
