//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBoy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recording_SB
    {
        public Recording_SB()
        {
            this.Track_Recording_Reln = new HashSet<Track_Recording_Reln>();
        }
    
        public string MB_Track_ID { get; set; }
        public Nullable<int> Position { get; set; }
        public string Song_Name { get; set; }
        public string Length { get; set; }
    
        public virtual ICollection<Track_Recording_Reln> Track_Recording_Reln { get; set; }
    }
}
