//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBoy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestContext : DbContext
    {
        public TestContext()
            : base("name=TestContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Album_SB> Album_SB { get; set; }
        public DbSet<Artist_SB> Artist_SB { get; set; }
        public DbSet<ID_SB> ID_SB { get; set; }
        public DbSet<Recording_SB> Recording_SB { get; set; }
        public DbSet<Track_Album_Reln> Track_Album_Reln { get; set; }
        public DbSet<Track_Artist_Reln> Track_Artist_Reln { get; set; }
        public DbSet<Track_Recording_Reln> Track_Recording_Reln { get; set; }
        public DbSet<Track_SB> Track_SB { get; set; }
    }
}
