//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBoy
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track_SB
    {
        public Track_SB()
        {
            this.ID_SB = new HashSet<ID_SB>();
            this.Track_Album_Reln = new HashSet<Track_Album_Reln>();
            this.Track_Artist_Reln = new HashSet<Track_Artist_Reln>();
        }
    
        public string MB_TrackID { get; set; }
        public string Title { get; set; }
        public Nullable<int> Counter { get; set; }
        public string MB_Release_Type { get; set; }
        public string Track_Content { get; set; }
        public string Lyrics { get; set; }
        public Nullable<int> Track_Image_ID { get; set; }
        public Nullable<int> Track { get; set; }
        public Nullable<int> Track_Count { get; set; }
        public Nullable<int> Disc { get; set; }
        public Nullable<int> Disc_Count { get; set; }
        public string MusicIP_ID { get; set; }
        public Nullable<int> Amazon_ID { get; set; }
        public Nullable<int> Track_length { get; set; }
        public Nullable<System.DateTime> Last_Played { get; set; }
    
        public virtual ICollection<ID_SB> ID_SB { get; set; }
        public virtual ICollection<Track_Album_Reln> Track_Album_Reln { get; set; }
        public virtual ICollection<Track_Artist_Reln> Track_Artist_Reln { get; set; }
    }
}
